


# https://fantasy.altonji.com/?code=9wbhwsn

https://fantasysports.yahooapis.com/fantasy/v2/users;use_login=1/
<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/users;use_login=1/" time="7.7230930328369ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
    <users count="1">
        <user>
            <guid>IYYZECV4YYWC3AQYEQPY3VSN6M</guid>
        </user>
    </users>
</fantasy_content>
<!-- fantasy-sports-api- -public-production-bf1-5dc45c7cc-6hdwx Wed May 13 05:10:32 UTC 2020 -->


https://fantasysports.yahooapis.com/fantasy/v2/users;use_login=1;out=teams
<team>
    <team_key>390.l.99174.t.7</team_key>
    <team_id>7</team_id>
    <name>1503 Sequoia Trail</name>
    <is_owned_by_current_login>1</is_owned_by_current_login>
    <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/7</url>
    <team_logos>
        <team_logo>
            <size>large</size>
            <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_3.png</url>
        </team_logo>
    </team_logos>
    <division_id>1</division_id>
    <waiver_priority>1</waiver_priority>
    <number_of_moves>26</number_of_moves>
    <number_of_trades>0</number_of_trades>
    <roster_adds>
        <coverage_type>week</coverage_type>
        <coverage_value>17</coverage_value>
        <value>0</value>
    </roster_adds>
    <league_scoring_type>head</league_scoring_type>
    <has_draft_grade>1</has_draft_grade>
    <draft_grade>A</draft_grade>
    <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/7/draftrecap</draft_recap_url>
    <managers>
        <manager>
            <manager_id>7</manager_id>
            <nickname>Chris A</nickname>
            <guid>IYYZECV4YYWC3AQYEQPY3VSN6M</guid>
            <is_current_login>1</is_current_login>
            <email>caltonji94@yahoo.com</email>
            <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
        </manager>
    </managers>
</team>

https://fantasysports.yahooapis.com/fantasy/v2/league/390.l.99174
<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/league/390.l.99174" time="17.992973327637ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
    <league>
        <league_key>390.l.99174</league_key>
        <league_id>99174</league_id>
        <name>Chyea In Da Buildin</name>
        <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174</url>
        <logo_url></logo_url>
        <draft_status>postdraft</draft_status>
        <num_teams>10</num_teams>
        <edit_key>16</edit_key>
        <weekly_deadline/>
        <league_update_timestamp>1577869735</league_update_timestamp>
        <scoring_type>head</scoring_type>
        <league_type>private</league_type>
        <renew>380_709344</renew>
        <renewed>399_43040</renewed>
        <iris_group_chat_id>IAILT7JKLJHYPFTQG2KBFRY6DA</iris_group_chat_id>
        <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
        <is_pro_league>0</is_pro_league>
        <is_cash_league>0</is_cash_league>
        <current_week>16</current_week>
        <start_week>1</start_week>
        <start_date>2019-09-05</start_date>
        <end_week>16</end_week>
        <end_date>2019-12-23</end_date>
        <is_finished>1</is_finished>
        <game_code>nfl</game_code>
        <season>2019</season>
    </league>
</fantasy_content>
<!-- fantasy-sports-api- -public-production-bf1-5dc45c7cc-zh528 Wed May 13 05:24:48 UTC 2020 -->


https://fantasysports.yahooapis.com/fantasy/v2/league/390.l.99174;out=teams
<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/league/390.l.99174;out=teams" time="248.83985519409ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
    <league>
        <league_key>390.l.99174</league_key>
        <league_id>99174</league_id>
        <name>Chyea In Da Buildin</name>
        <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174</url>
        <logo_url></logo_url>
        <draft_status>postdraft</draft_status>
        <num_teams>10</num_teams>
        <edit_key>16</edit_key>
        <weekly_deadline/>
        <league_update_timestamp>1577869735</league_update_timestamp>
        <scoring_type>head</scoring_type>
        <league_type>private</league_type>
        <renew>380_709344</renew>
        <renewed>399_43040</renewed>
        <iris_group_chat_id>IAILT7JKLJHYPFTQG2KBFRY6DA</iris_group_chat_id>
        <allow_add_to_dl_extra_pos>0</allow_add_to_dl_extra_pos>
        <is_pro_league>0</is_pro_league>
        <is_cash_league>0</is_cash_league>
        <current_week>16</current_week>
        <start_week>1</start_week>
        <start_date>2019-09-05</start_date>
        <end_week>16</end_week>
        <end_date>2019-12-23</end_date>
        <is_finished>1</is_finished>
        <game_code>nfl</game_code>
        <season>2019</season>
        <teams count="10">
            <team>
                <team_key>390.l.99174.t.1</team_key>
                <team_id>1</team_id>
                <name>Professor Teabag</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/1</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/59597098092_c11456.jpg</url>
                    </team_logo>
                </team_logos>
                <division_id>2</division_id>
                <waiver_priority>8</waiver_priority>
                <number_of_moves>33</number_of_moves>
                <number_of_trades>2</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <clinched_playoffs>1</clinched_playoffs>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>C+</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/1/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>1</manager_id>
                        <nickname>Miccyd</nickname>
                        <guid>IQ6KDAM5IPE2I2RPZ4UK2BB25Q</guid>
                        <is_commissioner>1</is_commissioner>
                        <email>miccydnestle@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.2</team_key>
                <team_id>2</team_id>
                <name>Champ</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/2</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_4_c.png</url>
                    </team_logo>
                </team_logos>
                <division_id>2</division_id>
                <waiver_priority>2</waiver_priority>
                <number_of_moves>27</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <clinched_playoffs>1</clinched_playoffs>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/2/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>2</manager_id>
                        <nickname>Simon Kim</nickname>
                        <guid>HL63GFVZHV23DRNQM2I6EA3D24</guid>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.3</team_key>
                <team_id>3</team_id>
                <name>Bottom Bitches</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/3</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_12.png</url>
                    </team_logo>
                </team_logos>
                <division_id>1</division_id>
                <waiver_priority>5</waiver_priority>
                <number_of_moves>31</number_of_moves>
                <number_of_trades>2</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/3/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>3</manager_id>
                        <nickname>Justin B</nickname>
                        <guid>MCG3DZCD2IM4SRRP63HIO37CUQ</guid>
                        <email>jbusiel@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.4</team_key>
                <team_id>4</team_id>
                <name>Hareem Kunt</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/4</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_11_k.png</url>
                    </team_logo>
                </team_logos>
                <division_id>2</division_id>
                <waiver_priority>3</waiver_priority>
                <number_of_moves>39</number_of_moves>
                <number_of_trades>1</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <clinched_playoffs>1</clinched_playoffs>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>C</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/4/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>4</manager_id>
                        <nickname>Paul Masini</nickname>
                        <guid>JWEOLZXJOALR6STDV5FUGVHP5A</guid>
                        <email>gbstitians360@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.5</team_key>
                <team_id>5</team_id>
                <name>Salmon Sisters</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/5</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/56504659123_d8ec0e.jpg</url>
                    </team_logo>
                </team_logos>
                <division_id>2</division_id>
                <waiver_priority>10</waiver_priority>
                <number_of_moves>40</number_of_moves>
                <number_of_trades>4</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <clinched_playoffs>1</clinched_playoffs>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/5/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>5</manager_id>
                        <nickname>Matt M</nickname>
                        <guid>5JQUSUGSFFCMSDUPMYBMZFAFNI</guid>
                        <email>millaman701@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/4693/38415055405_6b87f0_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.6</team_key>
                <team_id>6</team_id>
                <name>Hike School</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/6</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/37148768855_a66383.jpg</url>
                    </team_logo>
                </team_logos>
                <division_id>1</division_id>
                <waiver_priority>7</waiver_priority>
                <number_of_moves>21</number_of_moves>
                <number_of_trades>2</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <clinched_playoffs>1</clinched_playoffs>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>C</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/6/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>6</manager_id>
                        <nickname>J Remedy</nickname>
                        <guid>6PKXUMNCZ6JR35Z6A7LNN6YV3Q</guid>
                        <is_commissioner>1</is_commissioner>
                        <email>iowafan246@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.7</team_key>
                <team_id>7</team_id>
                <name>1503 Sequoia Trail</name>
                <is_owned_by_current_login>1</is_owned_by_current_login>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/7</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_3.png</url>
                    </team_logo>
                </team_logos>
                <division_id>1</division_id>
                <waiver_priority>1</waiver_priority>
                <number_of_moves>26</number_of_moves>
                <number_of_trades>0</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>A</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/7/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>7</manager_id>
                        <nickname>Chris A</nickname>
                        <guid>IYYZECV4YYWC3AQYEQPY3VSN6M</guid>
                        <is_current_login>1</is_current_login>
                        <email>caltonji94@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.8</team_key>
                <team_id>8</team_id>
                <name>Burrito House</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/8</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/56492739503_e9abff.jpg</url>
                    </team_logo>
                </team_logos>
                <division_id>1</division_id>
                <waiver_priority>9</waiver_priority>
                <number_of_moves>42</number_of_moves>
                <number_of_trades>1</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B+</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/8/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>8</manager_id>
                        <nickname>Greg A</nickname>
                        <guid>EERDPUH5UHFEHU7JJJUUQITSYI</guid>
                        <email>famguyfann23@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/4737/38428571834_c9c9e9_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.9</team_key>
                <team_id>9</team_id>
                <name>Pepper Brooks</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/9</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/23397812558_806642.jpg</url>
                    </team_logo>
                </team_logos>
                <division_id>2</division_id>
                <waiver_priority>6</waiver_priority>
                <number_of_moves>37</number_of_moves>
                <number_of_trades>1</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>B+</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/9/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>9</manager_id>
                        <nickname>Sam</nickname>
                        <guid>CZ7BILPSQHVRV3G6DMPBYUXR7E</guid>
                        <email>koloms24@yahoo.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
            <team>
                <team_key>390.l.99174.t.10</team_key>
                <team_id>10</team_id>
                <name>Bulgogi</name>
                <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/10</url>
                <team_logos>
                    <team_logo>
                        <size>large</size>
                        <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_1.png</url>
                    </team_logo>
                </team_logos>
                <division_id>1</division_id>
                <waiver_priority>4</waiver_priority>
                <number_of_moves>27</number_of_moves>
                <number_of_trades>1</number_of_trades>
                <roster_adds>
                    <coverage_type>week</coverage_type>
                    <coverage_value>17</coverage_value>
                    <value>0</value>
                </roster_adds>
                <clinched_playoffs>1</clinched_playoffs>
                <league_scoring_type>head</league_scoring_type>
                <has_draft_grade>1</has_draft_grade>
                <draft_grade>A-</draft_grade>
                <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/10/draftrecap</draft_recap_url>
                <managers>
                    <manager>
                        <manager_id>10</manager_id>
                        <nickname>Robert</nickname>
                        <guid>PTZR2COMVV3KPCQUPWYUKHZEN4</guid>
                        <email>rosirianni3@gmail.com</email>
                        <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                    </manager>
                </managers>
            </team>
        </teams>
    </league>
</fantasy_content>
<!-- fantasy-sports-api- -public-production-bf1-5dc45c7cc-prtvx Wed May 13 05:26:23 UTC 2020 -->

https://fantasysports.yahooapis.com/fantasy/v2/teams;team_keys=390.l.99174.t.1,390.l.99174.t.2,390.l.99174.t.3,390.l.99174.t.4,390.l.99174.t.5,390.l.99174.t.6,390.l.99174.t.7,390.l.99174.t.8,390.l.99174.t.9,390.l.99174.t.10
<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/teams;team_keys=390.l.99174.t.1,390.l.99174.t.2,390.l.99174.t.3,390.l.99174.t.4,390.l.99174.t.5,390.l.99174.t.6,390.l.99174.t.7,390.l.99174.t.8,390.l.99174.t.9,390.l.99174.t.10" time="144.29020881653ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
    <teams count="10">
        <team>
            <team_key>390.l.99174.t.1</team_key>
            <team_id>1</team_id>
            <name>Professor Teabag</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/1</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/59597098092_c11456.jpg</url>
                </team_logo>
            </team_logos>
            <division_id>2</division_id>
            <waiver_priority>8</waiver_priority>
            <number_of_moves>33</number_of_moves>
            <number_of_trades>2</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <clinched_playoffs>1</clinched_playoffs>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>C+</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/1/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>1</manager_id>
                    <nickname>Miccyd</nickname>
                    <guid>IQ6KDAM5IPE2I2RPZ4UK2BB25Q</guid>
                    <is_commissioner>1</is_commissioner>
                    <email>miccydnestle@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.2</team_key>
            <team_id>2</team_id>
            <name>Champ</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/2</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_4_c.png</url>
                </team_logo>
            </team_logos>
            <division_id>2</division_id>
            <waiver_priority>2</waiver_priority>
            <number_of_moves>27</number_of_moves>
            <number_of_trades>0</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <clinched_playoffs>1</clinched_playoffs>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>B</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/2/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>2</manager_id>
                    <nickname>Simon Kim</nickname>
                    <guid>HL63GFVZHV23DRNQM2I6EA3D24</guid>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.3</team_key>
            <team_id>3</team_id>
            <name>Bottom Bitches</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/3</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_12.png</url>
                </team_logo>
            </team_logos>
            <division_id>1</division_id>
            <waiver_priority>5</waiver_priority>
            <number_of_moves>31</number_of_moves>
            <number_of_trades>2</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>B</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/3/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>3</manager_id>
                    <nickname>Justin B</nickname>
                    <guid>MCG3DZCD2IM4SRRP63HIO37CUQ</guid>
                    <email>jbusiel@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.4</team_key>
            <team_id>4</team_id>
            <name>Hareem Kunt</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/4</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_11_k.png</url>
                </team_logo>
            </team_logos>
            <division_id>2</division_id>
            <waiver_priority>3</waiver_priority>
            <number_of_moves>39</number_of_moves>
            <number_of_trades>1</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <clinched_playoffs>1</clinched_playoffs>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>C</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/4/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>4</manager_id>
                    <nickname>Paul Masini</nickname>
                    <guid>JWEOLZXJOALR6STDV5FUGVHP5A</guid>
                    <email>gbstitians360@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.5</team_key>
            <team_id>5</team_id>
            <name>Salmon Sisters</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/5</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/56504659123_d8ec0e.jpg</url>
                </team_logo>
            </team_logos>
            <division_id>2</division_id>
            <waiver_priority>10</waiver_priority>
            <number_of_moves>40</number_of_moves>
            <number_of_trades>4</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <clinched_playoffs>1</clinched_playoffs>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>B</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/5/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>5</manager_id>
                    <nickname>Matt M</nickname>
                    <guid>5JQUSUGSFFCMSDUPMYBMZFAFNI</guid>
                    <email>millaman701@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/4693/38415055405_6b87f0_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.6</team_key>
            <team_id>6</team_id>
            <name>Hike School</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/6</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/37148768855_a66383.jpg</url>
                </team_logo>
            </team_logos>
            <division_id>1</division_id>
            <waiver_priority>7</waiver_priority>
            <number_of_moves>21</number_of_moves>
            <number_of_trades>2</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <clinched_playoffs>1</clinched_playoffs>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>C</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/6/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>6</manager_id>
                    <nickname>J Remedy</nickname>
                    <guid>6PKXUMNCZ6JR35Z6A7LNN6YV3Q</guid>
                    <is_commissioner>1</is_commissioner>
                    <email>iowafan246@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.7</team_key>
            <team_id>7</team_id>
            <name>1503 Sequoia Trail</name>
            <is_owned_by_current_login>1</is_owned_by_current_login>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/7</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_3.png</url>
                </team_logo>
            </team_logos>
            <division_id>1</division_id>
            <waiver_priority>1</waiver_priority>
            <number_of_moves>26</number_of_moves>
            <number_of_trades>0</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>A</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/7/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>7</manager_id>
                    <nickname>Chris A</nickname>
                    <guid>IYYZECV4YYWC3AQYEQPY3VSN6M</guid>
                    <is_current_login>1</is_current_login>
                    <email>caltonji94@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.8</team_key>
            <team_id>8</team_id>
            <name>Burrito House</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/8</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/56492739503_e9abff.jpg</url>
                </team_logo>
            </team_logos>
            <division_id>1</division_id>
            <waiver_priority>9</waiver_priority>
            <number_of_moves>42</number_of_moves>
            <number_of_trades>1</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>B+</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/8/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>8</manager_id>
                    <nickname>Greg A</nickname>
                    <guid>EERDPUH5UHFEHU7JJJUUQITSYI</guid>
                    <email>famguyfann23@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/4737/38428571834_c9c9e9_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.9</team_key>
            <team_id>9</team_id>
            <name>Pepper Brooks</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/9</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/23397812558_806642.jpg</url>
                </team_logo>
            </team_logos>
            <division_id>2</division_id>
            <waiver_priority>6</waiver_priority>
            <number_of_moves>37</number_of_moves>
            <number_of_trades>1</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>B+</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/9/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>9</manager_id>
                    <nickname>Sam</nickname>
                    <guid>CZ7BILPSQHVRV3G6DMPBYUXR7E</guid>
                    <email>koloms24@yahoo.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
        <team>
            <team_key>390.l.99174.t.10</team_key>
            <team_id>10</team_id>
            <name>Bulgogi</name>
            <url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/10</url>
            <team_logos>
                <team_logo>
                    <size>large</size>
                    <url>https://s.yimg.com/cv/apiv2/default/nfl/nfl_1.png</url>
                </team_logo>
            </team_logos>
            <division_id>1</division_id>
            <waiver_priority>4</waiver_priority>
            <number_of_moves>27</number_of_moves>
            <number_of_trades>1</number_of_trades>
            <roster_adds>
                <coverage_type>week</coverage_type>
                <coverage_value>17</coverage_value>
                <value>0</value>
            </roster_adds>
            <clinched_playoffs>1</clinched_playoffs>
            <league_scoring_type>head</league_scoring_type>
            <has_draft_grade>1</has_draft_grade>
            <draft_grade>A-</draft_grade>
            <draft_recap_url>https://football.fantasysports.yahoo.com/archive/nfl/2019/99174/10/draftrecap</draft_recap_url>
            <managers>
                <manager>
                    <manager_id>10</manager_id>
                    <nickname>Robert</nickname>
                    <guid>PTZR2COMVV3KPCQUPWYUKHZEN4</guid>
                    <email>rosirianni3@gmail.com</email>
                    <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
                </manager>
            </managers>
        </team>
    </teams>
</fantasy_content>
<!-- fantasy-sports-api- -public-production-bf1-5dc45c7cc-9ktf7 Wed May 13 05:32:19 UTC 2020 -->
